### ISSUE TITLE
Rust supports non-disableable lints

### ISSUE THREAD

**Issue by bjorn3** [jfmengels/blog#12]
I just read https://jfmengels.net/disable-comments/. I have a couple of comments. As your blog doesn't have a comment section I decided to open an issue here. Feel free to close it if you want.

> As far as I know, there is no static analysis tool out there that has disable comments and allows making some rules not disableable (please let me know if you know one!).

Rust has `#![forbid(lint_name)]` which can't be downgraded from a hard error to a warning or even completely silenced.

> Forbid constructs that lead to false results

While I agree with the intention of this, it would make adding new lints a breaking change. For example in Rust many lints are part of the compiler and thus checked during compilation. The Cargo build system forcefully disables all lints of dependencies even when using `#![forbid(lint_name)]` to ensure that adding a new lint to the compiler can never break compilation of a dependency even if it forbids all lints. For dependencies you would have to make a PR, wait for the maintainer to accept the change and then wait for a new version to be published. For your own code however you can easily change it to fix the lint, so a new lint breaking your build is less of a problem.

**Comment by jfmengels** [comment]
Hi @bjorn3 👋 

> Rust has #![forbid(lint_name)]

Could you possibly link to the documentation for this? Is this Clippy, or is this entirely baked into the Rust compiler (or both)? Is this a compiler error, or a static analysis tool error?

Where does this show up? In the linter's configuration, or in the code? I'm not sure I can discuss more without having a better grasp of how this works, but happy to once I learn more :)

> it would make adding new lints a breaking change

This depends on how the static analysis tool's rules are enforced. Rust seems to be a pretty peculiar one if the static analysis tool is built-in.

In my opinion, rules should be opt-in, so as not as to make addition or changes to rules be breaking changes. I know that `ESLint` a similar issue to what you're describing. It has a set of recommended rules, and they try to only make changes to this set of rules during major versions, which seems to be a bit of pain point for them as I understand it.

All rules being opt-in then poses a different question of discoverability and suggesting best practices, but that's a whole other topic, one for which I at the moment don't have a perfect solution for.

But coming back to the idea of forbidding constructs that lead to false results, this works well for custom rules (built only for a single project), which I don't think Clippy supports. I don't think this pattern should (often) be used in general-purpose rules. In Rust's case, if the static analysis tool and the compiler are the same, and they have general-purpose rules that would require the absence of some language features, then I think that maybe the language feature's existence should be re-evaluated by Rust's language committee. But I don't expect this to happen really.

**Comment by bjorn3** [comment]
> Could you possibly link to the documentation for this?

https://doc.rust-lang.org/reference/attributes/diagnostics.html#lint-check-attributes

> Is this Clippy, or is this entirely baked into the Rust compiler (or both)? Is this a compiler error, or a static analysis tool error?

Both. The compiler has a set of lints with a low false-positive rate that you likely want to keep enabled. Clippy has an additional set of lints which are more opinionated or with a higher false-positive rate. Most lints are set to warn by default. There are lints that are allowed by default, but most of them are restrictions that make sense for some projects, but not all. Examples of them are denying unsafe code or missing documentation.

> Where does this show up? In the linter's configuration, or in the code? I'm not sure I can discuss more without having a better grasp of how this works, but happy to once I learn more :)

Lints can be configured using arguments passed to rustc/clippy. For example `-A dead_code` allows the `dead_code` lint. `-D unsafe_code` denies (error) the `unsafe_code` lint. This is mostly useful on CI to for example deny all warnings using `RUSTFLAGS="-D warnings"`. Normally lints are configured in code using attributes like `#![allow(dead_code)]` or `#![warn(unsafe_code)]`. Attributes starting with `#![` are written at the top of a module and apply to all items within the module. Attributes starting with `#[` (without `!`) are written before the item they apply to. Clippy also allows configuring lints using the `clippy.toml` file. Rustc doesn't allow configuring lints using a file.

An example of globally denying all warn-by-default lints, but allowing the `dead_code` lint for `bar` would be:

```rust
#![deny(warnings)]

#[allow(dead_code)]
fn bar() {}
```

The equivalent with `#![forbid]` gives a compilation error:

```rust
#![forbid(dead_code)]

#[allow(dead_code)]
fn bar() {}
```

```
error[E0453]: allow(dead_code) incompatible with previous forbid
 --> src/lib.rs:3:9
  |
1 | #![forbid(dead_code)]
  |           --------- `forbid` level set here
2 | 
3 | #[allow(dead_code)]
  |         ^^^^^^^^^ overruled by previous forbid

error: aborting due to previous error
```

(with `#![forbid(warnings)]` it gives an unsilencable warning that this was previously incorrectly accepted due to a bug and will become a hard error in the future. rust has pretty strong backwards compatibility guarantees, so it can't be made a hard error directly)

> In my opinion, rules should be opt-in, so as not as to make addition or changes to rules be breaking changes.

Most lints are warn by default in rust. It is however possible to deny all warn-by-default lints using `#![deny(warnings)]`. While this would make adding new lints technically a breaking change, it has been chosen to not consider this a breaking change for user code as otherwise no new lints would be possible ever and in the worst case the `#![deny(warnings)]` can be removed. For dependencies `#![deny(warnings)]` can't be removed, so `--cap-lints` was introduced which cargo uses to suppress all lints for dependencies.

> I know that ESLint a similar issue to what you're describing. It has a set of recommended rules, and they try to only make changes to this set of rules during major versions, which seems to be a bit of pain point for them as I understand it.

It is not the intention to release a new major version of rustc for a very long time, so this solution is not possible for rustc.

> All rules being opt-in then poses a different question of discoverability and suggesting best practices, but that's a whole other topic, one for which I at the moment don't have a perfect solution for.

Yeah, I guess this is why lints are warnings by default in rust.

> But coming back to the idea of forbidding constructs that lead to false results, this works well for custom rules (built only for a single project), which I don't think Clippy supports. I don't think this pattern should (often) be used in general-purpose rules.

I see. Clippy indeed doesn't support custom lints. If you use nightly you can use internal compiler api's to write your own lints. There it is pretty easy to make lints truly unsuppressible by using `sess.struct_span_err` instead of `sess.struct_span_lint` to emit the error.

> In Rust's case, if the static analysis tool and the compiler are the same, and they have general-purpose rules that would require the absence of some language features, then I think that maybe the language feature's existence should be re-evaluated by Rust's language committee. But I don't expect this to happen really.

Clippy may have lints that don't work in the presence of some language features, but I think all rustc lints work fine with all language features except maybe newly introduced unstable features.
